[[redirects]]
  from = "/v1/*"
  to = "http://spaceflightnewsapi-dev.eu-central-1.elasticbeanstalk.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

