export {default as Header} from "./Header";
export {default as NewsCard} from "./cards/NewsCard";
export {default as ReportsCard} from "./cards/ReportsCard";
export {default as LatestNews} from "./LatestNews";
export {default as LatestBlogs} from "./LatestBlogs";
export {default as LatestReports} from "./LatestReports";
export {default as AppCard} from "./cards/AppCard";
export {default as Loading} from "./Loading";
export {default as CustomPaginate} from "./CustomPaginate";